### ISSUE TITLE
Document index sets and changes to index handling

### ISSUE THREAD

**Issue by bernd** [Graylog2/documentation#240]
The new index handling with index sets needs to be documented.

- [x] Explain migration path for existing users – #252
- [ ] Adapt existing documentation (index model) – #248
- [ ] Explain configuration options – #248
- [ ] Explain performance/storage usage implications – #248
- [ ] Sync changes with necessary changes of Archive plugin

**Comment by bernd** [comment]
Fixed in #248
